// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiOZbvBcWhCAa0f6XlGTCDMqYQEEdQdoY',
    appId: '1:189265632688:web:b668440ba49c4d23ff0a75',
    messagingSenderId: '189265632688',
    projectId: 'stellar-5',
    authDomain: 'stellar-5.firebaseapp.com',
    storageBucket: 'stellar-5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq8hOqlklGQ5b3IDaS0Q8JDgGQRplPKUY',
    appId: '1:189265632688:android:bde94e58dbd708a5ff0a75',
    messagingSenderId: '189265632688',
    projectId: 'stellar-5',
    storageBucket: 'stellar-5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4j2uNkqnbk6z1vRseGJ4DnygVDwayGLE',
    appId: '1:189265632688:ios:eb0f0cf06bdc7fb9ff0a75',
    messagingSenderId: '189265632688',
    projectId: 'stellar-5',
    storageBucket: 'stellar-5.appspot.com',
    iosBundleId: 'com.stellar.spaceGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4j2uNkqnbk6z1vRseGJ4DnygVDwayGLE',
    appId: '1:189265632688:ios:eb0f0cf06bdc7fb9ff0a75',
    messagingSenderId: '189265632688',
    projectId: 'stellar-5',
    storageBucket: 'stellar-5.appspot.com',
    iosBundleId: 'com.stellar.spaceGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiOZbvBcWhCAa0f6XlGTCDMqYQEEdQdoY',
    appId: '1:189265632688:web:234741ff6ad16c9dff0a75',
    messagingSenderId: '189265632688',
    projectId: 'stellar-5',
    authDomain: 'stellar-5.firebaseapp.com',
    storageBucket: 'stellar-5.appspot.com',
  );
}
